[technote]
id = "TSTN-047"
series_id = "TSTN"
canonical_url = "https://tstn-047.lsst.io"
github_url = "https://github.com/lsst-tstn/tstn-047"
github_default_branch = "main"
date_created = 2024-07-24T23:49:19Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[[technote.authors]]
name.given = "Fritz"
name.family = "Mueller"
internal_id = "muellerf"
orcid = "https://orcid.org/0000-0002-7061-4644"
[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
